### ISSUE TITLE
Arduino compatibility

### ISSUE THREAD

**Issue by bertrik** [fakufaku/esp32-fft#4]
Have you considered making this library 'Arduino compatible'?

I think this mostly just means putting the source code and examples in specific directories, adding a library.properties file and a library.json file. You probably don't have anything in there that is really hardware dependent.

**Comment by fakufaku** [comment]
Hi @bertrik , which platform would you target ? For the original 8-bit microprocessors on Arduino, the library is not very well adapted because it uses float precision.
I suppose for people using Arduino framework on other platform (such as esp32), it would make sense.
I indeed don't think the code is ESP32-specific at all.
I don't have the bandwidth to look into this immediately, but if you would like to propose something or make a pull request, I'd be ok going along with it.
