### ISSUE TITLE
Large sample array issue

### ISSUE THREAD

**Issue by Materie62** [fakufaku/esp32-fft#6]
Hi, I found your code and my ESP32 crashes whenever 'size' in fft_init becomes larger than 4096. I've seen the same problem with Arduinofft. In Arduinofft you need to define two double arrays (real and imag). If the two arrays become too large it will not fit in the ESP32 dram. When using Arduinofft and you define the arrays too large you will see a compiler warning. With your code there's no compiler error but the ESP32 simply crashes.
I need a large sample array because I want to create an class-I audiometer. For this you need to sample with a speed of 48kHz and for a duration of 125ms.
Can you confirm? And if so do you have a solution?

**Comment by fakufaku** [comment]
Hi @Materie62 , thanks for the report. I confirmed on my side that 8096 will crash. This is indeed caused by running out of memory. In my implementation, I dynamically allocate the arrays, which calls a malloc that fails and causes the esp32 to crash. In addition to the input and output buffers, I also use an array for the twiddle factors that is also dynamically allocated. I think this array may be larger than really needs to be. Another option would be to rewrite this in C++ and take advantage of the templating system to allocate the buffers on the stack so that compiler warnings could be triggered.

But in your case, I think you might be just able to run an 8096-point real FFT which only requires half the memory. I could successfully run an 8096-point real FFT and iFFT. Because `0.125 * 48000 = 6000`, this should be sufficient for your application.

**Comment by Materie62** [comment]
Hi fakufaku, first of all thanks a million for the fast response. Secondly, this a bummer that you can confirm... This really becomes a show stopper. Perhaps I have to resort to external memory or so.
In your code you use floats instead of the Arduinofft doubles. I was hoping this would save the day, but floats and doubles use 4 bytes so no solution there.
You are right about the array size of 6000. However your code tests if size is a power of two. I'm not sure if 6144 would be considered as a power of 2. 4096 and 8192 are.
Do you have other ideas?

**Comment by fakufaku** [comment]
For audio data, the input is real-valued, and for 6000 points, you can use a 8192 point FFT and zero pad the end. I have verified that this runs on the ESP32 I have here.

In addition, I am wondering if you really need such a long FFT. A long FFT is only needed if you need to have very fine frequency resolution. But for an audiometer, I suspect that you want to measure the energy in octave bands, or something like that. For that purpose, you don't need such a long FFT I think. You could use a short FFT and then average several frames to reach an analysis window of 125 ms.

**Comment by Materie62** [comment]
I found a solution! In the espressif/arduino-esp32 forum (https://github.com/espressif/arduino-esp32/issues/1163) you can find many posts on the ESP32 dram overflow issue when declaring large arrays. In one of the posts there is a mention that this overflow happens when defining array as globals. In an attempt to solve the issue I moved all the code to the setup region and run the fft code in a while(1) loop (in setup). Now the arrays become local and I could use 8192 points. So it has to do with how the ESP32 handles dram memory allocation. 
And yes indeed such a long FFT will give fine frequency seperation. But we are talking about 1/3 octave presentation not one octave. Using 6000 point @48kHz sampling rate would give 8Hz bins which fall exactly in the 1/3 octave bands.

**Comment by fakufaku** [comment]
Fantastic that you found a solution. And thanks for letting me know about this trick! Cheers.

**Comment by Materie62** [comment]
Hi Robin,

you're more than welcome. Happy to be of assistance.
Happy coding!

Greetings,

Roland


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
