### ISSUE TITLE
Arduino IDE, frequency ordering in input and output fields

### ISSUE THREAD

**Issue by DJ534** [fakufaku/esp32-fft#7]
Hi fakufaku,
I am using your library under arduino IDE and its working without any issues. On the code page of the project, I am missing the ordering of positive and negative frequencies in input and output fields for case of the complex numbers. Can you add it please?

To be precise, I mean: How an amplitude in the input (for IFFT) or output (for FFT) field of the complex numbers is related to its frequency. By trial and error I recognized, that the negative frequencies (for FFT) are ordered  from upper index - NFFT-1 downside and positive from index 0 upside. But I am not sure, if component with index NFFT/2 is related to highest positive of lowest negative frequency.

Thanks for explanation.

**Comment by fakufaku** [comment]
Hi, the library uses the standard ordering of frequencies for the complex FFT. Recall that the FFT is periodic so that `X_k == X_{N-k}`, where `N` is the FFT length. This means that `X_{-1} == X_{N-1}`, `X_{-2} == X_{N-2}`, and so on. Note that this is also the case in Matlab, numpy, etc.

For the real FFT, we do a small optimization (described in the README). Because both `X_0` and `X_{N/2}` are real, we store them together in the first two elements of the output array. In addition, real FFTs are conjugate symmetric in the frequency, i.e. `X_k == conj(X_{N-k})`, so that it is only needed to compute `X_0, ..., X_{N/2}`.
